export class ConfigMarkerValidator {
	validateMarkers(config: string): { valid: boolean; missing: string[] } {
		const requiredMarkers = [
			'CONFIG:SITE_URL',
			'CONFIG:SITE_TITLE',
			'CONFIG:SITE_DESCRIPTION',
			'CONFIG:SITE_AUTHOR',
			'CONFIG:SITE_LANGUAGE',
			'CONFIG:THEME',
			'CONFIG:AVAILABLE_THEMES',
			'CONFIG:FONT_SOURCE',
			'CONFIG:FONT_BODY',
			'CONFIG:FONT_HEADING',
			'CONFIG:FONT_MONO',
			'CONFIG:LAYOUT_CONTENT_WIDTH',
			'CONFIG:TABLE_OF_CONTENTS_ENABLED',
			'CONFIG:TABLE_OF_CONTENTS_DEPTH',
			'CONFIG:FOOTER_ENABLED',
			'CONFIG:FOOTER_SHOW_SOCIAL_ICONS',
			'CONFIG:SCROLL_TO_TOP',
			'CONFIG:FEATURE_BUTTON',
			'CONFIG:DEPLOYMENT_PLATFORM',
			'CONFIG:COMMAND_PALETTE_ENABLED',
			'CONFIG:COMMAND_PALETTE_SHORTCUT',
			'CONFIG:COMMAND_PALETTE_PLACEHOLDER',
			'CONFIG:COMMAND_PALETTE_SEARCH_POSTS',
			'CONFIG:COMMAND_PALETTE_SEARCH_PAGES',
			'CONFIG:COMMAND_PALETTE_SEARCH_PROJECTS',
			'CONFIG:COMMAND_PALETTE_SEARCH_DOCS',
			'CONFIG:COMMAND_PALETTE_SECTIONS_QUICK_ACTIONS',
			'CONFIG:COMMAND_PALETTE_SECTIONS_PAGES',
			'CONFIG:COMMAND_PALETTE_SECTIONS_SOCIAL',
			'CONFIG:COMMAND_PALETTE_QUICK_ACTIONS_ENABLED',
			'CONFIG:COMMAND_PALETTE_QUICK_ACTIONS_TOGGLE_MODE',
			'CONFIG:COMMAND_PALETTE_QUICK_ACTIONS_GRAPH_VIEW',
			'CONFIG:COMMAND_PALETTE_QUICK_ACTIONS_CHANGE_THEME',
			'CONFIG:PROFILE_PICTURE_ENABLED',
			'CONFIG:PROFILE_PICTURE_IMAGE',
			'CONFIG:PROFILE_PICTURE_ALT',
			'CONFIG:PROFILE_PICTURE_SIZE',
			'CONFIG:PROFILE_PICTURE_URL',
			'CONFIG:PROFILE_PICTURE_PLACEMENT',
			'CONFIG:PROFILE_PICTURE_STYLE',
			'CONFIG:NAVIGATION_SHOW_NAVIGATION',
			'CONFIG:NAVIGATION_STYLE',
			'CONFIG:NAVIGATION_SHOW_MOBILE_MENU',
			'CONFIG:NAVIGATION_PAGES',
			'CONFIG:NAVIGATION_SOCIAL',
			'CONFIG:OPTIONAL_CONTENT_TYPES_PROJECTS',
			'CONFIG:OPTIONAL_CONTENT_TYPES_DOCS',
			'CONFIG:HOME_OPTIONS_FEATURED_POST_ENABLED',
			'CONFIG:HOME_OPTIONS_FEATURED_POST_TYPE',
			'CONFIG:HOME_OPTIONS_FEATURED_POST_SLUG',
			'CONFIG:HOME_OPTIONS_RECENT_POSTS_ENABLED',
			'CONFIG:HOME_OPTIONS_RECENT_POSTS_COUNT',
			'CONFIG:HOME_OPTIONS_PROJECTS_ENABLED',
			'CONFIG:HOME_OPTIONS_PROJECTS_COUNT',
			'CONFIG:HOME_OPTIONS_DOCS_ENABLED',
			'CONFIG:HOME_OPTIONS_DOCS_COUNT',
			'CONFIG:HOME_OPTIONS_BLURB_PLACEMENT',
			'CONFIG:POST_OPTIONS_POSTS_PER_PAGE',
			'CONFIG:POST_OPTIONS_READING_TIME',
			'CONFIG:POST_OPTIONS_WORD_COUNT',
			'CONFIG:POST_OPTIONS_TAGS',
			'CONFIG:POST_OPTIONS_LINKED_MENTIONS_ENABLED',
			'CONFIG:POST_OPTIONS_LINKED_MENTIONS_COMPACT',
			'CONFIG:POST_OPTIONS_GRAPH_VIEW_ENABLED',
			'CONFIG:POST_OPTIONS_GRAPH_VIEW_SHOW_IN_SIDEBAR',
			'CONFIG:POST_OPTIONS_GRAPH_VIEW_MAX_NODES',
			'CONFIG:POST_OPTIONS_GRAPH_VIEW_SHOW_ORPHANED_POSTS',
			'CONFIG:POST_OPTIONS_POST_NAVIGATION',
			'CONFIG:POST_OPTIONS_SHOW_POST_CARD_COVER_IMAGES',
			'CONFIG:POST_OPTIONS_POST_CARD_ASPECT_RATIO',
			'CONFIG:POST_OPTIONS_CUSTOM_POST_CARD_ASPECT_RATIO',
			'CONFIG:POST_OPTIONS_COMMENTS_ENABLED',
			'CONFIG:POST_OPTIONS_COMMENTS_PROVIDER',
			'CONFIG:POST_OPTIONS_COMMENTS_REPO',
			'CONFIG:POST_OPTIONS_COMMENTS_REPO_ID',
			'CONFIG:POST_OPTIONS_COMMENTS_CATEGORY',
			'CONFIG:POST_OPTIONS_COMMENTS_CATEGORY_ID',
			'CONFIG:POST_OPTIONS_COMMENTS_MAPPING',
			'CONFIG:POST_OPTIONS_COMMENTS_STRICT',
			'CONFIG:POST_OPTIONS_COMMENTS_REACTIONS',
			'CONFIG:POST_OPTIONS_COMMENTS_METADATA',
			'CONFIG:POST_OPTIONS_COMMENTS_INPUT_POSITION',
			'CONFIG:POST_OPTIONS_COMMENTS_THEME',
			'CONFIG:POST_OPTIONS_COMMENTS_LANG',
			'CONFIG:POST_OPTIONS_COMMENTS_LOADING'
		];
		
		const missing = requiredMarkers.filter(marker => 
			!config.includes(`// [${marker}]`)
		);
		
		return { valid: missing.length === 0, missing };
	}

	validateSyntax(config: string): { valid: boolean; errors: string[] } {
		const errors: string[] = [];
		
		try {
			// Check for basic syntax issues
			const openBraces = (config.match(/\{/g) || []).length;
			const closeBraces = (config.match(/\}/g) || []).length;
			const openBrackets = (config.match(/\[/g) || []).length;
			const closeBrackets = (config.match(/\]/g) || []).length;
			
			if (openBraces !== closeBraces) {
				errors.push('Mismatched braces');
			}
			
			if (openBrackets !== closeBrackets) {
				errors.push('Mismatched brackets');
			}
			
		} catch (error) {
			errors.push(`Validation failed: ${error instanceof Error ? error.message : String(error)}`);
		}
		
		return { valid: errors.length === 0, errors };
	}
}
